[phases.setup]
nixpkgs = ["nodejs_22_x"]   # try nodejs_22_x if nodejs_22 is not found

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
